### ISSUE TITLE
Replace uploading files to old storage when using uploadFile

### ISSUE THREAD

**Issue by sceiler** [saucelabs/saucerest-java#192]
## Further comments

**Comment by EdouardTomberg** [comment]
Hello Sceiler,

We are from National Bank of Canada which is a client of SauceLabs. We have our own Framework for Automation which is actively using SauceLabs. Our new module for mobile testing needs to automate all aspects of the process including uploading mobile application file to the SauceLabs storage. I was happy to find the SauceREST Java client library doing the job. It was so easy to use! Unfortunately it uploads files to the "old" storage and when I pass the returned app ID to the Appium capabilities the SauceLabs cannot find the application because it searches for it in the "new" storage.

I see that you have added the bug request for the same issue. Is it possible to fix it ASAP. I will appreciate it a lot. We have tens of huge test automation projects here at the bank waiting for this mobile module.

Thank you!

Edouard Tomberg
Senior solution architect

Cordialement,

 

Edouard Tomberg,

**Comment by sceiler** [comment]
Hi,

Yes I plan to work on this as soon as possible. However I currently don't have a time line I can share with you. 

At the moment I plan to do multiple fixes and implement features which would break compatibility with the current released version. If I push a fix are you comfortable building the jar yourself? That would speed it up and you wouldn't have to wait for us to release a new version to Maven. 

Let me know what you think.

**Comment by EdouardTomberg** [comment]
Hello,

Sure, we can build the jar as a temporary solution. Once the new release is ready we can replace this jar with it.

Thank you,

Edouard Tomberg, Ph.D.
Architecte senior de solution / Senior Solution Architect
Opérations et Performance TI / IT Operations and Performance

    [devops-2lignes-300px]
***@***.******@***.***>
[BN_2D_RGB]
Banque Nationale du Canada
700, Rue De La Gauchetière Ouest, Montréal,Québec, Canada, H3B 4L2
8e étage
