### ISSUE TITLE
Can't find release notes for 1.0.42

### ISSUE THREAD

**Issue by mrk-han** [saucelabs/saucerest-java#82]
Hey! Was wondering if I am blanking out or if release notes just aren't published.

Thanks

**Comment by enriquegh** [comment]
@mrk-han don't believe we've ever had release notes.
You might be thinking of our jenkins plugin:
https://github.com/jenkinsci/sauce-ondemand-plugin

that does have release notes.

**Comment by sceiler** [comment]
@mrk-han 
You could use the release page and the commits since then to master to get a change log based on commit messages. For example, https://github.com/saucelabs/saucerest-java/releases/tag/saucerest-1.0.44 and here you can click on "25 commits since ..." to see all commits done after the release of 1.0.44.
